name: smartsilencerapp

description: A Flutter app that silences the phone based on prayer times and location.

publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Prayer time & calendar
  adhan: ^2.0.0
  hijri: ^3.0.0

  # Location & permissions
  shared_preferences: ^2.2.2
  location: ^8.0.0
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1

  # Notifications
  flutter_local_notifications: ^19.2.1

  # Android-specific integrations
  android_intent_plus: ^5.3.0
  flutter_background_service: ^5.0.5

  # Network
  http: ^1.4.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
